/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_InfoCpu */

#ifndef _Included_jni_InfoCpu
#define _Included_jni_InfoCpu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_InfoCpu
 * Method:    getInfoCpu
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_InfoCpu_getInfoCpu
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
